services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pedidos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede-pedidos
    # Adiciona a verificação para saber quando o banco está pronto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pedidos_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pedidos:
    build: .
    container_name: pedidos
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/pedidos_db
    depends_on:
      postgres:
        # Garante que a API só inicia DEPOIS que o banco estiver saudável
        condition: service_healthy
    networks:
      - rede-pedidos

volumes:
  postgres_data:

networks:
  rede-pedidos:
    driver: bridge